[package]
name = "hmac"
version = "0.0.2"
description = "Motoko library for HMAC generation and verification"
repository = "https://github.com/edjCase/motoko_hmac"
keywords = [ "hmac", "key" ]
license = "Apache-2.0"

[dependencies]
sha2 = "0.1.0"
core = "0.6.0"

[dev-dependencies]
bench = "1.0.0"
test = "2.1.1"