[package]
name = "hmac"
version = "1.1.0"
description = "Motoko library for HMAC generation and verification"
repository = "https://github.com/edjCase/motoko_hmac"
keywords = ["hmac", "key", "cryptography"]
license = "Apache-2.0"

[dependencies]
"sha2@0" = "0.1.6"
"core@1" = "1.0.0"

[dev-dependencies]
bench = "1.0.0"
test = "2.1.1"
